# Generated by Django 4.2.29 on 2026-04-07 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_uppercase_and_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    mapping = {
        "admin": "ADMIN",
        "trainer": "TRAINER",
        "finance": "FINANCE",
        "student": "STUDENT",
    }
    for u in User.objects.all():
        t = getattr(u, "user_type", None)
        if t in mapping:
            u.user_type = mapping[t]
            u.save(update_fields=["user_type"])
    for u in User.objects.all():
        e = (u.email or "").strip()
        if not e:
            u.email = f"user{u.pk}@placeholder.local"
            u.save(update_fields=["email"])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_type"),
    ]

    operations = [
        migrations.RunPython(forwards_uppercase_and_emails, backwards_noop),
        migrations.AlterField(
            model_name="trainerprofile",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "TRAINER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("TRAINER", "Trainer"),
                    ("FINANCE", "Finance"),
                    ("STUDENT", "Student"),
                ],
                db_index=True,
                default="STUDENT",
                max_length=32,
            ),
        ),
    ]
