# Generated by Django 4.2.29 on 2026-04-09 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_address_student_gender'),
        ('accounts', '0004_user_can_manage_assessments_user_can_manage_finance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('TRAINER', 'Trainer'), ('FINANCE', 'Finance'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], db_index=True, default='STUDENT', max_length=32),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('relationship_note', models.CharField(blank=True, max_length=255)),
                ('students', models.ManyToManyField(blank=True, related_name='parent_profiles', to='students.student')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
