# Generated by Django 4.2.29 on 2026-04-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('ADMISSION', 'Admission Officer'), ('ADMISSION_FINANCE', 'Admission & Finance Officer'), ('TRAINER', 'Lecturer'), ('FINANCE', 'Finance'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], db_index=True, default='STUDENT', max_length=32),
        ),
    ]
