# Generated by Django 4.2.29 on 2026-04-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_feestructure_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=120)),
                ('checkout_request_id', models.CharField(blank=True, max_length=120)),
                ('result_code', models.IntegerField(default=0)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('transaction_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('account_reference', models.CharField(blank=True, max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_logs', to='finance.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
