# Generated by Django 4.2.29 on 2026-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('statement', models.TextField()),
            ],
            options={
                'ordering': ['unit', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['unit', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('L4', 'TVET Level 4'), ('L5', 'TVET Level 5'), ('L6', 'TVET Level 6')], db_index=True, max_length=8)),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('total_credit_hours', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective')], default='core', max_length=16)),
                ('credit_hours', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['program', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UnitTrainerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('can_assess', models.BooleanField(default=True, help_text='Trainer may record assessments for this unit (subject to qualifications).')),
            ],
        ),
    ]
