# Generated by Django 4.2.29 on 2026-04-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittrainerassignment',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.PROTECT, related_name='unit_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unittrainerassignment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='academics.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.program'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='academics.unit'),
        ),
        migrations.AddField(
            model_name='competencyunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='academics.unit'),
        ),
        migrations.AddConstraint(
            model_name='unittrainerassignment',
            constraint=models.UniqueConstraint(fields=('unit', 'trainer'), name='unique_trainer_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('program', 'code'), name='unique_unit_code_per_program'),
        ),
        migrations.AddConstraint(
            model_name='competencyunit',
            constraint=models.UniqueConstraint(fields=('unit', 'code'), name='unique_competency_code_per_unit'),
        ),
    ]
