# Generated by Django 4.2.29 on 2026-04-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_address_student_gender'),
        ('academics', '0003_alter_unittrainerassignment_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='academics.unit'),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2')], default='S1', max_length=8)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('dropped', 'Dropped')], default='registered', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='students.enrollment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academics.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(fields=('enrollment', 'unit', 'semester'), name='unique_unit_registration_per_semester'),
        ),
    ]
