# Generated by Django 4.2.29 on 2026-04-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campus'),
        ('academics', '0004_unit_prerequisites_courseregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='core.campus'),
        ),
    ]
