# Generated by Django 4.2.29 on 2026-04-10 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_enrollment_mode_of_study_student_guardian_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0005_program_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('level_label', models.CharField(blank=True, help_text='e.g. Beginner, Intermediate, Advanced', max_length=64)),
                ('duration_value', models.PositiveSmallIntegerField(default=1)),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='weeks', max_length=16)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule_notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'level_label'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='course_type',
            field=models.CharField(choices=[('TVET_PROGRAM', 'TVET Program'), ('SHORT_COURSE', 'Short Course')], db_index=True, default='TVET_PROGRAM', max_length=20),
        ),
        migrations.CreateModel(
            name='ShortCourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('short_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.shortcourse')),
            ],
            options={
                'ordering': ['-session_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShortCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=16)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('short_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.shortcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_course_enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-enrolled_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShortCourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='academics.shortcourseenrollment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortCourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=16)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.shortcourseenrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.shortcoursesession')),
            ],
            options={
                'ordering': ['-marked_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='shortcourseenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'short_course'), name='unique_student_short_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='shortcourseattendance',
            constraint=models.UniqueConstraint(fields=('session', 'enrollment'), name='unique_short_course_attendance_session_enrollment'),
        ),
    ]
