# Generated by Django 4.2.29 on 2026-04-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_shortcourse_program_course_type_shortcoursesession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['code'], 'verbose_name': 'Academic Program', 'verbose_name_plural': 'Academic Programs'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['program', 'code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='unittrainerassignment',
            options={'verbose_name': 'Lecturer Assignment', 'verbose_name_plural': 'Lecturer Assignments'},
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_years',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unittrainerassignment',
            name='semester',
            field=models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3')], default='S1', max_length=8),
        ),
        migrations.AlterField(
            model_name='program',
            name='total_credit_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unittrainerassignment',
            name='can_assess',
            field=models.BooleanField(default=True, help_text='Deprecated: retained for compatibility.'),
        ),
    ]
