# Generated by Django 4.2.29 on 2026-04-10 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0007_alter_program_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcourse',
            options={'ordering': ['name', 'level_label'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='shortcourse',
            name='course_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='shortcourse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shortcourse',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16),
        ),
        migrations.AddField(
            model_name='shortcoursesession',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_course_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortcoursesession',
            name='session_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortcourseenrollment',
            name='enrolled_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='shortcourseenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='ShortCoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mpesa', 'M-Pesa')], default='mpesa', max_length=16)),
                ('mpesa_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('paid_on', models.DateField(auto_now_add=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.shortcourseenrollment')),
            ],
            options={
                'ordering': ['-paid_on', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortCourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_rating', models.PositiveSmallIntegerField(blank=True, help_text='Score between 1 and 100', null=True)),
                ('outcome', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=8)),
                ('remarks', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.shortcourseenrollment')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_course_assessments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='academics.shortcoursesession')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
