# Generated by Django 4.2.29 on 2026-04-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_shortcourse_options_shortcourse_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcourse',
            name='category',
            field=models.CharField(choices=[('ict', 'ICT'), ('language', 'Language'), ('skill', 'Skill')], db_index=True, default='ict', max_length=16),
        ),
    ]
