# Generated by Django 4.2.29 on 2026-04-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_shortcourse_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcoursesession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortcoursesession',
            name='location',
            field=models.CharField(blank=True, help_text='Room name or online meeting link', max_length=255),
        ),
        migrations.AddField(
            model_name='shortcoursesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16),
        ),
    ]
