# Generated by Django 4.2.29 on 2026-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_shortcoursesession_end_time_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shortcoursepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_reference', ''), _negated=True), fields=('mpesa_reference',), name='unique_short_course_mpesa_reference'),
        ),
    ]
