# Generated by Django 4.2.29 on 2026-04-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], db_index=True, default='active', max_length=20)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('certificate_eligible', models.BooleanField(default=False, help_text='Set when all program competencies are met and results approved.')),
            ],
            options={
                'ordering': ['-enrolled_on'],
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (5, 'May'), (9, 'September')])),
                ('year', models.PositiveSmallIntegerField()),
                ('label', models.CharField(help_text='e.g. "Jan 2026"', max_length=64)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('kcse_summary', models.TextField(blank=True, help_text='KCSE grades / summary as entered at admission.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deferred', 'Deferred'), ('graduated', 'Graduated'), ('discontinued', 'Discontinued')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='student_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'National ID / Passport'), ('kcse', 'KCSE certificate'), ('certificate', 'Other certificate'), ('transcript', 'Transcript')], max_length=32)),
                ('file', models.FileField(upload_to='student_docs/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='intake',
            constraint=models.UniqueConstraint(fields=('month', 'year'), name='unique_intake_month_year'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.intake'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.program'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'program'), name='unique_student_program_enrollment'),
        ),
    ]
