# Generated by Django 4.2.29 on 2026-04-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campus'),
        ('students', '0004_student_address_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.campus'),
        ),
    ]
