# Generated by Django 4.2.29 on 2026-04-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_program_campus'),
        ('students', '0005_enrollment_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='mode_of_study',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='kcse_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='UnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_assignments', to='students.enrollment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_assignments', to='academics.unit')),
            ],
            options={
                'ordering': ['unit__title'],
            },
        ),
        migrations.AddConstraint(
            model_name='unitassignment',
            constraint=models.UniqueConstraint(fields=('enrollment', 'unit'), name='unique_unit_assignment_per_enrollment'),
        ),
    ]
