# Generated by Django 4.2.29 on 2026-04-07 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'TRAINER'}, on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
