# Generated by Django 4.2.29 on 2026-04-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='TVET College', max_length=255)),
                ('academic_year', models.CharField(default='2026', max_length=32)),
                ('intake_periods', models.CharField(default='January, May, September', help_text='Comma-separated intake periods.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
