# Generated by Django 4.2.29 on 2026-04-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='current_semester',
            field=models.CharField(default='Semester 1', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='grading_system',
            field=models.TextField(default='A:80-100,B:70-79,C:60-69,D:50-59,F:0-49', help_text='Simple grade scale definition.'),
        ),
    ]
