# Generated by Django 4.2.29 on 2026-04-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsetting_current_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='institution_name',
            field=models.CharField(default='College Management System', max_length=255),
        ),
    ]
