# Generated by Django 4.2.29 on 2026-04-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('practical', 'Practical'), ('theory', 'Theory'), ('industrial_attachment', 'Industrial attachment')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.competencyunit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.unit')),
            ],
            options={
                'ordering': ['unit', 'competency', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('grade', models.CharField(blank=True, choices=[('C', 'Competent'), ('NYC', 'Not Yet Competent')], max_length=8)),
                ('comments', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attempts', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='students.enrollment')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentUnitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_grade', models.CharField(blank=True, choices=[('C', 'Competent'), ('NYC', 'Not Yet Competent')], help_text='C only when all competencies in the unit are met with evidence.', max_length=8)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_results', to='students.enrollment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='academics.unit')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assessment_evidence/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='assessments.assessmentattempt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentunitresult',
            constraint=models.UniqueConstraint(fields=('enrollment', 'unit'), name='unique_student_unit_result'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('enrollment', 'assessment', 'attempt_number'), name='unique_attempt_number_per_enrollment_assessment'),
        ),
    ]
