# Generated by Django 4.2.29 on 2026-04-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentattempt_score_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('cat', 'CAT'), ('main', 'Main Exam'), ('practical', 'Practical'), ('theory', 'Theory'), ('industrial_attachment', 'Industrial attachment')], max_length=32),
        ),
    ]
