# Generated by Django 4.2.29 on 2026-04-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_max_score_assessment_pass_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2),
        ),
    ]
