from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("admin-dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("admission-dashboard/", views.admission_dashboard, name="admission_dashboard"),
    path("admission-finance-dashboard/", views.admission_finance_dashboard, name="admission_finance_dashboard"),
    path("trainer-dashboard/", views.trainer_dashboard, name="trainer_dashboard"),
    path("finance-dashboard/", views.finance_dashboard, name="finance_dashboard"),
    path("student-dashboard/", views.student_dashboard, name="student_dashboard"),
    path("student/downloads/results-slip/", views.student_results_slip_download, name="student_results_slip_download"),
    path("student/downloads/fee-statement/", views.student_fee_statement_download, name="student_fee_statement_download"),
    path(
        "student/downloads/short-course-certificate/<int:certificate_id>/",
        views.short_course_certificate_download,
        name="short_course_certificate_download",
    ),
    path("parent-dashboard/", views.parent_dashboard, name="parent_dashboard"),
    path("student/courses/", views.course_registration, name="course_registration"),
    path("admin/users/", views.user_management, name="user_management"),
    path("admin/users/<int:user_id>/edit/", views.user_update, name="user_update"),
    path("admin/users/<int:user_id>/toggle-active/", views.user_toggle_active, name="user_toggle_active"),
    path("admin/users/<int:user_id>/reset-password/", views.user_reset_password, name="user_reset_password"),
    path("admin/students/", views.student_management, name="student_management"),
    path("admin/admissions/", views.admission_applications, name="admission_applications"),
    path("admin/students/<int:student_id>/", views.student_profile, name="student_profile"),
    path("admin/students/<int:student_id>/transcript.pdf", views.transcript_pdf, name="student_transcript_pdf"),
    path("admin/courses/", views.cbet_management, name="cbet_management"),
    path("admin/programs-courses/", views.cbet_management, name="programs_courses_legacy"),
    path("admin/cbet/", views.cbet_management, name="cbet_legacy"),
    path("admin/exams/", views.assessment_management, name="assessment_management"),
    path("admin/assessments/", views.assessment_management, name="assessment_legacy"),
    path("admin/results/", views.results_management, name="results_management"),
    path("admin/finance/", views.finance_management, name="finance_management"),
    path("admin/finance/receipt/<int:payment_id>/", views.payment_receipt, name="payment_receipt"),
    path("admin/timetable/", views.timetable_management, name="timetable_management"),
    path("admin/library/", views.library_management, name="library_management"),
    path("admin/communications/", views.communication_management, name="communication_management"),
    path("admin/approvals/", views.approvals_management, name="approvals_management"),
    path("admin/audit-logs/", views.audit_logs, name="audit_logs"),
    path("admin/attachments/", views.attachment_management, name="attachment_management"),
    path("admin/reports/", views.reports_management, name="reports_management"),
    path("admin/settings/", views.system_settings, name="system_settings"),
]
